const {chromium}=require('./.browser-tools/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const create=await page.request.post('http://127.0.0.1:5001/api/ops',{data:{op:'GESTAO-'+Date.now(),referencia:'Jeans <teste>',qtd:{M:100},peso_unit:{M:.8}}});
  assert.equal(create.status(),200);const {id}=await create.json();
  await page.goto('http://127.0.0.1:5001');
  await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
  await page.getByRole('button',{name:'Acompanhamento de OPs',exact:true}).click();
  await page.locator('#gestao-actor').fill('Gestora de teste');
  await page.locator(`[data-ficha="${id}"]`).click();
  await page.locator('#g-client').fill('Cliente de teste');
  await page.locator('#g-revenue').fill('1000');
  await page.getByRole('button',{name:'Salvar dados da OP',exact:true}).click();
  await page.getByText('Registro salvo.',{exact:true}).waitFor();
  await page.getByText('Configurar roteiro e responsáveis',{exact:true}).click();
  await page.getByRole('button',{name:'Adicionar etapa',exact:true}).click();
  await page.locator('.g-route-row select').selectOption('qualidade');
  await page.locator('.g-route-row input').fill('Ana');
  await page.getByRole('button',{name:'Salvar roteiro',exact:true}).click();
  await page.getByRole('button',{name:'Iniciar Qualidade',exact:true}).click();
  await page.getByRole('button',{name:'Concluir Qualidade',exact:true}).click();
  await page.getByText('1. Qualidade',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Adicionar custo',exact:true}).click();
  await page.locator('#gd-cat').selectOption('energia');
  await page.locator('#gd-desc').fill('Energia medida');
  await page.locator('#gd-unit').fill('kWh');
  await page.locator('#gd-qty').fill('100');
  await page.locator('#gd-price').fill('2');
  await page.locator('#gestao-dialog').getByRole('button',{name:'Confirmar',exact:true}).click();
  await page.getByRole('button',{name:'Apontar realizado',exact:true}).click();
  await page.locator('#gd-qty').fill('90');
  await page.locator('#gd-price').fill('2');
  await page.locator('#gestao-dialog').getByRole('button',{name:'Confirmar',exact:true}).click();
  await page.locator('#gestao-dialog').waitFor({state:'hidden'});
  assert.equal((await page.request.get(`http://127.0.0.1:5001/api/gestao/ops/${id}`)).ok(),true);
  const detail=await (await page.request.get(`http://127.0.0.1:5001/api/gestao/ops/${id}`)).json();
  assert.equal(detail.custos.total_real,180);assert.equal(detail.custos.margem_prevista,800);assert.equal(detail.concluida,true);
  const price=await page.request.post('http://127.0.0.1:5001/api/precos',{data:{op:detail.op,referencia:detail.referencia,preco_peca:10}});
  assert.equal(price.status(),200);
  await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
  await page.getByRole('button',{name:'Faturamento',exact:true}).click();
  await page.getByRole('button',{name:'OPs Prontas',exact:false}).click();
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('#prontas-tbody tr').filter({hasText:detail.op}).getByRole('button',{name:'Faturar',exact:true}).click();
  await page.locator('#prontas-tbody tr').filter({hasText:detail.op}).getByText('Faturada',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
  await page.getByRole('button',{name:'Acompanhamento de OPs',exact:true}).click();
  await page.locator(`[data-ficha="${id}"]`).click();
  await page.locator('#g-client').waitFor();
  const invoiced=await (await page.request.get(`http://127.0.0.1:5001/api/gestao/ops/${id}`)).json();
  assert.equal(invoiced.custos.margem_real,820);
  fs.mkdirSync('test-results',{recursive:true});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/gestao-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/gestao-celular.png',fullPage:true});
  await page.evaluate(id=>deleteOp(id),id);
  await page.locator('#gd-reason').fill('OP encerrada');
  await page.locator('#gestao-dialog').getByRole('button',{name:'Confirmar',exact:true}).click();
  await page.locator('#gestao-dialog').waitFor({state:'hidden'});
  await page.evaluate(()=>goPage('arquivados'));
  await page.locator(`[data-history="${id}"][data-type="ops"]`).click();
  await page.getByText('Histórico do cadastro',{exact:true}).waitFor();
  await page.locator('#gd-close').click();
  await page.locator(`[data-restore="${id}"][data-type="ops"]`).click();
  await page.locator('#gestao-dialog').getByRole('button',{name:'Confirmar',exact:true}).click();
  await page.getByText('Nenhum cadastro arquivado.',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('OK: ficha, roteiro, custos previstos/realizados, celular, arquivamento, histórico e restauração.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
