const {chromium}=require('./.browser-tools/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:5001');
  await page.getByText('Operação agora',{exact:true}).waitFor();
  assert.equal(await page.locator('.operation-stage').count(),3);
  fs.mkdirSync('test-results',{recursive:true});
  await page.screenshot({path:'test-results/painel-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Abrir modo operador',exact:true}).click();
  await page.locator('.operator-card').waitFor();
  assert.equal(await page.locator('#operator-machine option').count(),27);
  await page.getByRole('button',{name:'Iniciar',exact:true}).click();
  await page.getByText('Informe seu nome antes de registrar a ação.',{exact:true}).waitFor();
  await page.locator('#operator-name').fill('Operadora de teste');
  await page.getByRole('button',{name:'Iniciar',exact:true}).click();
  await page.getByRole('button',{name:'Pausar',exact:true}).waitFor();
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  await page.getByText('Informe o motivo da pausa.',{exact:true}).waitFor();
  await page.locator('textarea[id^="pause-"]').fill('Troca de insumo');
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  await page.getByRole('button',{name:'Retomar',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.locator('#sidebar').evaluate(el=>el.getBoundingClientRect().right<=0),true);
  await page.getByRole('button',{name:'Abrir menu',exact:true}).click();
  await page.getByRole('button',{name:'Fechar menu',exact:true}).click({position:{x:380,y:400}});
  await page.screenshot({path:'test-results/operador-celular.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await page.getByRole('button',{name:'Retomar',exact:true}).click();
  await page.getByRole('button',{name:'Concluir',exact:true}).click();
  await page.getByRole('heading',{name:/Concluir carga/}).waitFor();
  await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  await page.getByRole('button',{name:'Concluir',exact:true}).click();
  await page.getByRole('heading',{name:/Concluir carga/}).waitFor();
  await page.locator('#conclusao-peso').fill('80');
  await page.locator('#conclusao-pecas').fill('100');
  await page.getByRole('button',{name:'Confirmar conclusão',exact:true}).click();
  await page.getByText('Nenhuma carga nesta seleção.',{exact:false}).waitFor();
  await page.locator('#operator-completed').check();
  await page.getByText('Concluído',{exact:true}).waitFor();
  await page.getByText('Histórico de apontamentos (4)',{exact:true}).waitFor();
  await page.evaluate(()=>goPage('dashboard'));
  await page.getByText('80 kg realizados',{exact:true}).waitFor();
  const created=await page.request.post('http://127.0.0.1:5001/api/ops',
    {data:{op:'CONFIRMACAO',referencia:'Teste',qtd:{M:29},peso_unit:{M:0.7}}});
  assert.equal(created.status(),200);
  const flow=await require('./test_fluxo_helpers.cjs').programar(page,'http://127.0.0.1:5001',(await created.json()).id);
  const carga={id:flow.etapas[1].vinculos[0].carga_id};
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>openMaqPanel(2,'lavar',2));
  await page.locator(`#cr-${carga.id} select`).selectOption('concluido');
  await page.getByRole('heading',{name:/Concluir carga/}).waitFor();
  await page.locator('#conclusao-peso').fill('19.5');
  await page.locator('#conclusao-pecas').fill('29');
  await page.getByRole('button',{name:'Confirmar conclusão',exact:true}).click();
  await page.locator('#conclusao-dialog').waitFor({state:'hidden'});
  const queue=await (await page.request.get('http://127.0.0.1:5001/api/operacao/maquinas/2')).json();
  const done=queue.cargas.find(c=>c.id===carga.id);
  assert.equal(done.status,'concluido');
  assert.equal(done.historico.length,1);
  assert.equal(done.historico[0].peso,19.5);
  assert.equal(done.historico[0].pecas,29);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  assert.deepEqual(errors,[]);
  console.log('OK: painel, 27 máquinas, ciclo completo, validações, histórico e layout móvel.');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
