const {chromium}=require('./.browser-tools/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const base='http://127.0.0.1:5001',name='FLUXO-'+Date.now();
  const recipe=await page.request.post(base+'/api/receitas',{data:{nome:'Receita de teste',etapas:[{titulo:'Preparar',tempo_min:20,instrucao_texto:'Conferir lote'}]}});
  assert.equal(recipe.status(),200);const rid=(await recipe.json()).id;
  await page.goto(base+'/estoque-seco');
  await page.locator('#actor').fill('Responsável teste');
  await page.locator('#new-op').click();
  await page.locator('#op-number').fill(name);await page.locator('#op-reference').fill('JEANS');
  await page.locator('[data-q="M"]').fill('101');await page.locator('#save').click();
  await page.locator('#editor').waitFor({state:'hidden'});
  await page.locator('#configure').click();await page.locator('#route-name').fill('Dupla fase final');
  await page.locator('#main-recipe').selectOption(String(rid));
  await page.locator('.route-row').nth(3).getByRole('button',{name:'Retirar fase',exact:true}).click();
  await page.locator('.phase').nth(2).selectOption('passadoria_final');
  await page.locator('.phase').nth(3).selectOption('laser_final');
  await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
  await page.locator('#move').click();await page.locator('#destination').selectOption('2');await page.locator('#save').click();
  await page.locator('#form-error').filter({hasText:'Peso'}).waitFor();await page.locator('#cancel').click();
  await page.locator('#edit-op').click();await page.locator('[data-p="M"]').fill('0.8');
  await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
  await page.locator('#move').click();await page.locator('#destination').selectOption('2');await page.locator('#save').click();
  await page.locator('#editor').waitFor({state:'hidden'});
  const ops=await (await page.request.get(base+'/api/fluxo/ops')).json();const oid=ops.find(o=>o.op===name).id;
  const url=base+'/api/fluxo/ops/'+oid;
  let detail=await (await page.request.get(url)).json();
  assert.equal(detail.etapas[1].vinculos.length,2);
  assert.equal(await page.locator('#move').count(),0);
  fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/fluxo-desktop.png',fullPage:true});
  const queue=(await (await page.request.get(base+'/api/operacao/maquinas/2')).json()).cargas;
  for(const v of detail.etapas[1].vinculos){const c=queue.find(c=>c.id===v.carga_id);
   const r=await page.request.post(base+`/api/operacao/cargas/${c.id}/apontar`,{data:{acao:'concluir',operador:'Ana',revisao:0,peso:c.peso,pecas:c.pecas}});assert.equal(r.status(),200);
  }
  await page.locator('#refresh-op').click();await page.locator('#move').click();await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
  detail=await (await page.request.get(url)).json();const pid=detail.etapas[2].vinculos[0].passadoria_id;
  await page.goto(base+'/?pagina=passadoria');
  page.once('dialog',d=>d.accept('Operadora de teste'));
  await page.evaluate(async id=>{await api(`/api/passadoria/fila/${id}`,'PUT',{status:'concluido'});},pid);
  detail=await (await page.request.get(url)).json();assert.equal(detail.pronta,false);assert.equal(detail.etapas[2].status,'concluido');
  await page.goto(base+'/estoque-seco?op='+oid);await page.locator('#actor').fill('Ana');
  await page.locator('#move').click();await page.locator('#destination').selectOption('1');await page.locator('#save').click();await page.locator('#editor').waitFor({state:'hidden'});
  detail=await (await page.request.get(url)).json();const lid=detail.etapas[3].vinculos[0].laser_id;
  await page.goto(base+'/?pagina=laser');page.once('dialog',d=>d.accept('Operador laser'));
  await page.evaluate(async id=>{await api(`/api/laser/fila/${id}`,'PUT',{status:'concluido'});},lid);
  await page.goto(base+'/estoque-seco?op='+oid);await page.getByText('OP pronta e liberada para faturamento.',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'test-results/fluxo-celular.png',fullPage:true});
  await page.goto(base+'/?pagina=ops');await page.locator('#ops-tbody').getByRole('link',{name:'Estoque / roteiro'}).first().waitFor();
  assert.deepEqual(errors,[]);
  console.log('OK: cadastro, pesos obrigatórios, roteiro próprio, transferência, duas cargas, filas existentes, última fase e celular.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
